# Generated by Django 4.2.7 on 2023-11-27 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_order_address_order_phonenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phonenumber',
            new_name='phone',
        ),
    ]
